# Generated by Django 4.1.5 on 2023-01-09 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0002_alter_record_qay_sana_remove_record_talaba_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kitob',
            name='muallif',
        ),
        migrations.RemoveField(
            model_name='record',
            name='talaba',
        ),
        migrations.AddField(
            model_name='kitob',
            name='muallif',
            field=models.ManyToManyField(to='asosiy.muallif'),
        ),
        migrations.AddField(
            model_name='record',
            name='talaba',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='asosiy.talaba'),
            preserve_default=False,
        ),
    ]
